spring:
  application:
    name: calendaroptimizer
  datasource:
    url: jdbc:postgresql://localhost:5432/property_rental
    username: admin
    password: admin123
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: validate  # Changed from 'update' to prevent schema auto-generation
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/calendar-realm